# Generated by Django 5.0 on 2024-01-01 00:30

import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_kategori', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LikePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.CharField(max_length=500, null=True)),
                ('video_id', models.CharField(max_length=500, null=True)),
                ('modul_id', models.CharField(max_length=500, null=True)),
                ('audio_id', models.CharField(max_length=500, null=True)),
                ('username', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Lisensi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_lisensi', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id_post', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('judul', models.CharField(max_length=100)),
                ('deskripsi', models.TextField(blank=True)),
                ('thumbnail', models.ImageField(null=True, upload_to='post_thumbnail')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('no_of_like', models.IntegerField(default=0)),
                ('kategori_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.kategori')),
                ('lisensi_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.lisensi')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='post_images')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.post')),
            ],
        ),
        migrations.CreateModel(
            name='PostModul',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('thumbnail', models.ImageField(null=True, upload_to='post_thumbnail')),
                ('file_modul', models.FileField(null=True, upload_to='post_moduls')),
                ('judul', models.CharField(max_length=100)),
                ('deskripsi', models.TextField()),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('no_of_like', models.IntegerField(default=0)),
                ('kategori_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.kategori')),
                ('lisensi_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.lisensi')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PostVideo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('thumbnail', models.ImageField(null=True, upload_to='post_thumbnail')),
                ('file_video', models.FileField(null=True, upload_to='post_videos')),
                ('link_video', models.CharField(max_length=255, null=True)),
                ('judul', models.CharField(max_length=100)),
                ('deskripsi', models.TextField()),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('no_of_like', models.IntegerField(default=0)),
                ('kategori_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.kategori')),
                ('lisensi_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.lisensi')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.IntegerField()),
                ('profile_image', models.ImageField(default='blank-profile-picture.png', upload_to='profile_images')),
                ('alamat', models.TextField(blank=True)),
                ('tanggal_lahir', models.DateField(blank=True, null=True)),
                ('nama_lengkap', models.CharField(blank=True, max_length=100)),
                ('no_hp', models.CharField(blank=True, max_length=20)),
                ('jenis_kelamin', models.CharField(blank=True, max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
