# Generated by Django 5.0 on 2024-01-02 07:14

import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostAudio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('thumbnail', models.ImageField(null=True, upload_to='post_thumbnail')),
                ('file_audio', models.FileField(null=True, upload_to='post_audios')),
                ('judul', models.CharField(max_length=100)),
                ('deskripsi', models.TextField()),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('no_of_like', models.IntegerField(default=0)),
                ('kategori_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.kategori')),
                ('lisensi_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.lisensi')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
